name: jbindgen CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: bootstrap a debian
      run: |
        sudo apt-get install debootstrap -y
        sudo debootstrap sid ../sid https://deb.debian.org/debian/
        sudo mount -B /proc ../sid/proc
        sudo mkdir ../sid/project
        sudo mkdir ../sid/extra
        sudo chmod -R 777 ../sid/project
        sudo chmod -R 777 ../sid/extra
        sudo chroot ../sid /bin/env -i /bin/bash -c "useradd test"
        cp -r * ../sid/project
    - name: install depends
      run: |
        sudo chroot ../sid /bin/env -i /bin/bash -c "apt-get install libclang-16-dev clang-16 llvm-16-dev cmake make g++ openjdk-21-jdk-headless openjdk-22-jdk-headless -y --no-install-suggests --no-install-recommends "
        cd ../sid/extra/
        wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
        unzip gradle-8.5-bin.zip
    - name: cmake configure
      run: sudo chroot ../sid /bin/su -l test -c /bin/bash -c "cd /project && cmake -B build"
    - name: cmake build
      run: sudo chroot ../sid /bin/su -l test -c /bin/bash -c "cd /project/build && cmake --build . -j"
    - name: cmake run tests
      run: sudo chroot ../sid /bin/su -l test -c /bin/bash -c "cd /project/build && ctest --output-on-failure -R assimp"
    - name: move generation files
      run: sudo chroot ../sid /bin/su -l test -c /bin/bash -c "cd /project/build && mkdir -p src/main/java && mv generation/* src/main/java"
    - name: generate gradle files
      run: |
        build_gradle="plugins {
                          id 'java'
                          id 'java-library'
                      }

                      compileJava {
                          options.compilerArgs += ['--enable-preview']
                      }
                      java {
                          toolchain {
                              languageVersion = JavaLanguageVersion.of(22)
                          }
                      }"
        echo "$build_gradle" > build.gradle
        settings_gradle="rootProject.name = 'build'"
        echo "$settings_gradle" > settings.gradle
        sudo mv build.gradle ../sid/project/build
        sudo mv settings.gradle ../sid/project/build
    - name: gradle build
      run: sudo chroot ../sid /bin/su -l test -c /bin/bash -c "cd /project && export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && bash /extra/gradle-8.5/bin/gradle build --stacktrace"
